DROP DATABASE IF EXISTS OTPS_SYSTEM;

CREATE DATABASE IF NOT EXISTS OTPS_SYSTEM;
USE OTPS_SYSTEM;

DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PRODUCTLIST;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE USER
(
	USER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	USER_USERNAME VARCHAR(30) NOT NULL,
	USER_PASSWORD VARCHAR(20) NOT NULL,
	USER_EMAIL VARCHAR(40) NOT NULL,
	USER_PHONE VARCHAR(10),
	USER_ADDRESS VARCHAR(100),
	USER_ISADMIN BOOLEAN NOT NULL

);

CREATE TABLE ADMIN
(
	USER_ID INT NOT NULL PRIMARY KEY ,
	ADMIN_CODE VARCHAR(20) NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE

);

CREATE TABLE ORDERS
(
	ORDER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ACC_ID INT NOT NULL,
	SALES_TOTAL DOUBLE NOT NULL,
	ORDER_DATE TIMESTAMP NOT NULL, 
	ORDER_STATUS ENUM('Shipped','UnShipped','Cancelled') NOT NULL,
	ORDER_ADDRESS VARCHAR(100) NOT NULL,
	CC_NUMBER VARCHAR(20) NOT NULL,
	CC_TYPE ENUM('Discover','Visa','MasterCard','AmericanExpress','none') NOT NULL,
	CSV_NUM VARCHAR(4) NOT NULL,
	EXP_DATE DATE NOT NULL,
	ORDER_ISPAID BOOLEAN NOT NULL,
	FOREIGN KEY(ACC_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);


CREATE TABLE PRODUCT
(
	PROD_ID	INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PROD_NAME VARCHAR(100) NOT NULL,
	PROD_PRICE DOUBLE NOT NULL,
	PROD_QUANTITY SMALLINT NOT NULL
);

CREATE TABLE PRODUCT_RATING
(
	PROD_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	PROD_RATING DOUBLE NOT NULL,
	CONSTRAINT PR_ID PRIMARY KEY (PROD_ID,USER_ID),
	FOREIGN KEY(PROD_ID) REFERENCES PRODUCT(PROD_ID) ON DELETE CASCADE,
	FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);


CREATE TABLE PRODUCTLIST
(
	ORDER_ID INT NOT NULL ,
	PROD_ID INT NOT NULL ,
	PL_QUANTITY SMALLINT NOT NULL,
	CONSTRAINT PL_ID PRIMARY KEY (ORDER_ID,PROD_ID),
	FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
	FOREIGN KEY(PROD_ID) REFERENCES PRODUCT(PROD_ID) ON DELETE CASCADE
);



